# Generated by Django 3.2.7 on 2021-10-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.CharField(blank=True, default='', max_length=100)),
                ('answer', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
