# Generated by Django 3.2.7 on 2021-10-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitymonitor',
            name='cards_seen',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activitymonitor',
            name='time_spent',
            field=models.IntegerField(default=0),
        ),
    ]
