# Generated by Django 3.2.7 on 2021-10-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrelation',
            name='related_id',
        ),
        migrations.AddField(
            model_name='userrelation',
            name='friends',
            field=models.ManyToManyField(related_name='friends', to='api.User'),
        ),
        migrations.AddField(
            model_name='userrelation',
            name='owner',
            field=models.ManyToManyField(related_name='owner', to='api.User'),
        ),
    ]
