# Generated by Django 3.2.7 on 2021-10-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211017_0728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrelation',
            name='friends',
        ),
        migrations.AddField(
            model_name='user',
            name='relations',
            field=models.ManyToManyField(blank=True, to='api.User'),
        ),
        migrations.AddField(
            model_name='userrelation',
            name='friends_of_owner',
            field=models.ManyToManyField(related_name='friends_of_owner', to='api.User'),
        ),
    ]
