# Generated by Django 3.2.7 on 2021-10-22 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211022_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcard',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
