# Generated by Django 3.2.7 on 2021-10-22 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_owner_flashcard_owner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashdeck',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
