# Generated by Django 3.2.7 on 2021-10-23 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_owner_flashdeck_owner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcard',
            old_name='flash_deck_id',
            new_name='flash_deck',
        ),
        migrations.RenameField(
            model_name='flashcard',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='flashcarduser',
            old_name='flashcard_id',
            new_name='flashcard',
        ),
        migrations.RenameField(
            model_name='flashdeck',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
