# Generated by Django 3.2.7 on 2021-10-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211023_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcarduser',
            name='last_opened',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flashcarduser',
            name='last_time_taken',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flashcarduser',
            name='next_scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
